// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbcwhoegxzrlzghvzzqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiY3dob2VneHpybHpnaHZ6enFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODAwNjAsImV4cCI6MjA2MTA1NjA2MH0.FdYIcj6eUHHRM7zUi0tMGsXOch9P-O3f_eN__hwfZNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);